opacity-rule = [
    "70:class_g = 'kitty'",
    /* "90:class_g = 'TelegramDesktop'", */
]

backend = "glx";
blur: 
{
    method = "dual_kawase";
    strength = 3;
}

corner-radius = 12;


animations = true;
animation-for-open-window = "zoom";
animation-window-mass = 0.5
animation-dampening = 20
