#!/usr/bin/env bash

# aliases
my_dir="$(dirname "$0")"
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# keybinds
source "$my_dir/keybinds.sh"

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# theme
my_dir="$(dirname "$0")"
source "$my_dir/theme.sh"

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

# try some custom hooks, yeh??
hc rule title='Telegram' tag=3 switchtag=on floating=on floating_geometry=960x1000

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# autostart
libinput-gestures-setup start
xset r rate 210 40

killall polybar
polybar &

# wallpaper
wpname=q.*
feh --no-fehbg --bg-fill /home/me/arch/wp/$wpname
